# Generated by Django 3.1.7 on 2021-03-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210321_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=45, verbose_name='Nome')),
                ('icone', models.CharField(choices=[('lni-rocket', ''), ('lni-laptop-phone', ''), ('lni-cog', ''), ('lni-leaf', 'Folha'), ('lni-layers', '')], max_length=12, verbose_name='Icone')),
                ('descricao', models.TextField(max_length=300, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'recurso',
                'verbose_name_plural': 'recursos',
            },
        ),
    ]
