# Generated by Django 3.1.7 on 2021-03-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_recurso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='icone',
            field=models.CharField(choices=[('lni-rocket', 'Foguete'), ('lni-laptop-phone', 'Laptop'), ('lni-cog', 'Designer'), ('lni-leaf', 'Folha'), ('lni-layers', 'Engrenagem')], max_length=16, verbose_name='Icone'),
        ),
    ]
